name: yamllint

on:
  pull_request:
    paths:
      - "**/*.yml"
      - "**/*.yaml"
      - ".yamllint"
      - ".github/workflows/yamllint.yml"
  workflow_dispatch:

permissions:
  contents: read

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  yamllint:
    name: yamllint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2

      - name: Run yamllint
        run: yamllint .
